# Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.

import fnmatch
from dataclasses import dataclass, field
from typing import Callable, Optional, Tuple, Union, Literal

import torch

from ..utils import is_te_min_version


@dataclass(frozen=True)
class ParamPredicate:
    """Wraps a matching function to make it hashable for ParamKey.
    Example:
        >>> shape_1_param = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param(torch.empty(10))
        True
        >>> shape_1_param_copy = ParamPredicate(name="s1", fn=lambda param: len(param.shape) == 1)
        >>> shape_1_param == shape_1_param_copy  # name is used to match
        True
        >>> {shape_1_param, shape_1_param_copy} == {shape_1_param}  # set hashing works properly

    NOTE:
        __hash__ and __eq__ are automatically generated by @dataclass(frozen=True)
        based solely on 'name' because we set compare=False/hash=False on 'fn'.
    """

    name: str
    fn: Callable[[torch.nn.Parameter], bool] = field(compare=False, hash=False)

    def __call__(self, param: torch.nn.Parameter) -> bool:
        return self.fn(param)


@dataclass(frozen=True, slots=True)
class ParamKey:
    """Key to group parameters by. All such grouped parameters can share an
    optimizer config specification."""

    # TODO: Can add layer_id here later.

    name: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter name(s), will use unix filesystem path syntax for matching."""

    attr: Union[str, Tuple[str]] = field(default_factory=tuple)
    """Parameter attribute(s)."""

    predicate: Union[ParamPredicate, Tuple[ParamPredicate]] = field(default_factory=tuple)
    """Predicate(s) to match parameters by. If multiple predicates are provided, any must match."""

    def matches(self, param: torch.nn.Parameter, param_name: str) -> bool:
        """Returns true if passed-in parameter (with name) matches `param_key`.

        Args:
            param (torch.nn.Parameter): Handle to parameter object.
            param_name (str): Name of parameter in underlying PyTorch module.

        Returns:
            bool: True if parameter matches passed-in param_key.
        """

        # Check if name matches.
        if isinstance(self.name, str):
            target_names = [self.name]
        else:
            target_names = list(self.name)
        for target_name in target_names:
            if fnmatch.fnmatch(param_name, target_name):
                return True

        # Check if attribute matches.
        if isinstance(self.attr, str):
            target_attrs = [self.attr]
        else:
            target_attrs = list(self.attr)
        for target_attr in target_attrs:
            if getattr(param, target_attr, False):
                return True

        # Check if predicate matches.
        if isinstance(self.predicate, ParamPredicate):
            if self.predicate(param):
                return True
        else:
            for predicate in self.predicate:
                if predicate(param):
                    return True
        return False


@dataclass
class OptimizerConfig:
    """Base optimizer configuration object."""

    ##############
    # General
    ##############

    lr: Optional[float] = None
    """Initial learning rate. Depending on decay style and initial warmup, the learning rate at each
       iteration would be different.
    """

    min_lr: Optional[float] = None
    """Minumum value for learning rate. The scheduler clip values below this threshold."""

    weight_decay: float = 0.01
    """Weight decay coefficient for L2 regularization."""

    ##############
    # Precision
    ##############
    fp8_recipe: Optional[str] = None
    """The type of fp8 recipe will affect the processing logic inside distributed optimizer."""

    fp16: bool = False
    """If true, train with fp16 mixed precision training. Defaults to False."""

    bf16: bool = False
    """If true, train with bf16 mixed precision training. Defaults to False."""

    reuse_grad_buf_for_mxfp8_param_ag: bool = False
    """If true, reuse the grad buffer for param AG when using mxfp8 recipe. Should be 
       set to True only when fp8_recipe is mxfp8 and fp8_param_gather is True."""

    params_dtype: torch.dtype = torch.float32
    """dtype used when intializing the weights. Defaults to torch.float32."""

    use_precision_aware_optimizer: bool = False
    """If true, allows optimizer-related tensors (master_param, gradients and optimizer states)
    to be set to lower precision. Defaults to False.
    """

    store_param_remainders: bool = True
    """If true, store the 16-bit FP32 parameter remainders in the optimizer state, excluding the
        16 bits shared with the BF16 parameters. This lowers GPU memory usage. Defaults to True.
    """

    main_grads_dtype: torch.dtype = torch.float32
    """dtype of main grads when enabling precision-aware-optimizer"""

    main_params_dtype: torch.dtype = torch.float32
    """dtype of main params when enabling precision-aware-optimizer"""

    exp_avg_dtype: torch.dtype = torch.float32
    """dtype of exp_avg when enabling precision-aware-optimizer"""

    exp_avg_sq_dtype: torch.dtype = torch.float32
    """dtype of exp_avg_sq when enabling precision-aware-optimizer"""

    optimizer: str = 'adam'
    """Optimizer name. NOTE: Deprecated, use individual optimizer classes instead."""

    ###############
    # Loss scaling
    ###############
    loss_scale: Optional[float] = None
    """Static loss scaling, positive power of 2 values can improve fp16 convergence. If None,
       dynamic loss scaling is used.
    """

    initial_loss_scale: float = 2**32
    """Initial loss-scale for dynamic loss scaling."""

    min_loss_scale: float = 1.0
    """Minimum loss scale for dynamic loss scaling."""

    loss_scale_window: float = 1000
    """Window over which to raise/lower dynamic scale."""

    hysteresis: int = 2
    """Hysteresis for dynamic loss scaling."""

    ###################################################################################
    # Optimizer (NOTE: Deprecated, use individual optimizer classes instead.).
    ###################################################################################
    # Adam.
    adam_beta1: float = 0.9
    """First coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_beta2: float = 0.999
    """Second coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_eps: float = 1e-08
    """Term added to the denominator to improve numerical stability in Adam optimizer."""

    decoupled_weight_decay: bool = True
    """If true, decouples weight decay from the gradient update, equivalent to AdamW. If false,
    original Adam update rule will be used. Defaults to True.
    """

    # SGD.
    sgd_momentum: float = 0.9
    """Momentum factor for SGD optimizer."""

    # Muon.
    # TODO: move muon configs to it's own `MuonConfig`.
    muon_momentum: float = 0.95
    """The momentum used by the internal SGD."""

    muon_split_qkv: bool = True
    """Whether to split QKV parameters for Muon optimizer."""

    muon_use_nesterov: bool = False
    """Whether to use Nesterov-style momentum in the internal SGD."""

    muon_scale_mode: str = "spectral"
    """The mode to use for the scale factor. Defaults to "spectral"."""

    muon_fp32_matmul_prec: str = "medium"
    """The precision to use for the fp32 matmul. Defaults to "medium"."""

    muon_num_ns_steps: int = 5
    """The number of iteration steps to use in the Newton-Schulz iteration."""

    muon_tp_mode: str = "blockwise"
    """How to perform NS calculation for tensor parallel weights. Defaults to "blockwise"."""

    muon_extra_scale_factor: float = 1.0
    """Additional scale factor for the muon update."""

    muon_lr_factor: float = 1.0
    """Muon parameters will use a learning rate of lr * muon_lr_factor instead of just lr."""

    matrix_lr: Optional[float] = None
    """Absolute learning rate for matrix (linear) parameters. When set, overrides
    muon_lr_factor * lr so the matrix LR is independent of the base LR."""

    embedding_lr_multiplier: Optional[float] = None
    """Embedding/output parameters will use lr * embedding_lr_multiplier.
    If None, falls back to muon_lr_factor * lr."""

    embedding_lr: Optional[float] = None
    """Absolute learning rate for the input embedding. When set, overrides
    embedding_lr_multiplier * lr. Applied regardless of whether embeddings
    are inside the master optimizer (--hs-embed) or in the chained adam path."""

    output_lr: Optional[float] = None
    """Absolute learning rate for the LM head output layer when untied.
    When set, overrides the default (which is base lr when embedding_lr_multiplier
    is set, or matrix_lr otherwise)."""

    scale_min_lr: bool = False
    """When True, each param group's min_lr is scaled proportionally to its max_lr,
    keeping the same max_lr/min_lr ratio as the base (lr / min_lr)."""

    hypersphere_mode: Optional[Literal["row", "col", "rowcol", "flat"]] = None
    """When specified, enables hypersphere constraint of the parameters, either row-wise, column-wise, row+column-wise or of the flattened vector."""

    hypersphere_gains_mode: Optional[Literal["row", "col", "rowcol", "flat", "embed", "lowrank"]] = None
    """When specified, enables learnable gains for matrices :). "lowrank" learns a rank-k
    multiplier G = 1 + A@B (A:[m,k], B:[k,n], k = gains_rank) applied elementwise to the
    weight — the full-capacity generalisation of the rank-1 "rowcol" mode."""

    hypersphere_gains_mode_output: Optional[Literal["row", "col", "rowcol", "flat", "lowrank", "none"]] = None
    """When specified, overrides the gains mode for the final LM head (output layer).
    If None, the output layer uses hypersphere_gains_mode like all other matrices.
    Set to "none" to disable gains on the output layer entirely."""

    hypersphere_gains_mode_embedding: Optional[Literal["row", "col", "rowcol", "flat", "lowrank", "none"]] = None
    """When specified, overrides the gains mode for the embedding (input) layer.
    If None, the embedding layer uses hypersphere_gains_mode like all other matrices.
    Set to "none" to disable gains on the embedding layer entirely."""

    split_qkv_gains: bool = False
    """When True and col gains are active, QKV parameters get separate column gains for Q, K, and V instead of one shared column gain."""

    gains_lr: Optional[float] = None
    """Absolute learning rate for gain parameters. When None, gains follow the param group LR (i.e. the same schedule as the weights they scale)."""

    gains_beta1: Optional[float] = None
    """Adam beta1 for the gain optimizer. When None, reuses adam_beta1."""

    gains_beta2: Optional[float] = None
    """Adam beta2 for the gain optimizer. When None, reuses adam_beta2."""

    gains_eps: Optional[float] = None
    """Adam eps for the gain optimizer. When None, reuses adam_eps."""

    gains_weight_decay: Optional[float] = None
    """Weight decay for gain parameters. When None, reuses weight_decay."""

    gains_bias_correction: bool = True
    """Whether to apply Adam bias correction (the 1-beta^t terms) in the gain optimizer."""

    gains_min: float = 0.0
    """Floor on the effective multiplier phi(g). After each gain step the raw gain is clamped to
    g >= phi^-1(gains_min), keeping phi(g) >= gains_min. Prevents gains collapsing toward/through
    zero (sign flips for direct), and keeps the undo division p/phi(g) bounded in every mode.
    0 disables. Parametrization-agnostic: e.g. gains_min=1e-5 maps to raw clamp 1e-5 (direct),
    ~-11.5 (softplus/exp), ~-1.0 (offset)."""

    gain_parametrization: Literal["direct", "offset", "softplus", "exp"] = "direct"
    """How the learned gain `g` maps to the effective multiplier `phi(g)` applied to W_bare.
    - "direct":   phi(g) = g           (current behaviour; identity-init = 1.0)
    - "offset":   phi(g) = 1 + g       (identity-init = 0.0; wd attractor is identity)
    - "softplus": phi(g) = softplus(g) (identity-init = ln(e-1); phi'(g) = sigmoid(g) caps
                                       per-step change in phi(g) to ~lr, mitigating sudden
                                       grad-norm spikes from heavy-tailed gain gradients)."""

    gains_rank: int = 4
    """Rank k of the "lowrank" gains multiplier G = 1 + A@B. Capped at min(m, n) per param.
    k=1 recovers a single rank-1 correction (cf. the multiplicative rowcol mode)."""

    gains_lowrank_init_std: Optional[float] = None
    """Init std for the random A factor of the lowrank gains (B is initialised to zero, so the
    multiplier is exactly identity at init). When None, defaults to (1/k)**0.5."""

    gains_lowrank_min: float = 1e-2
    """Floor on the effective lowrank multiplier G = 1 + A@B (applied as clamp_min on G, used
    identically on undo and re-apply so the round-trip stays exact). The additive A@B correction
    is unbounded and can drift an entry of G toward/past zero (especially with weight_decay=0),
    which would blow up the undo division p/G and trigger a small-G -> large-gain runaway. The
    floor bounds the undo at 1/gains_lowrank_min. <= 0 falls back to a tiny eps (1e-8)."""

    hypersphere_preserve_init: bool = False
    """When True, skip the init-time projection onto the hypersphere. With gains, the init
    norms are absorbed into the gains so the effective weight (p * gains) equals the original
    init. Without gains, the bare parameter is left as-is and the first optimizer step projects
    it onto the sphere."""

    hypersphere_kind: Optional[Literal["l2", "standard", "spectral"]] = "l2"
    """When hypersphere constraint is enabled, specified the normalization to perform, either l2 normalization, (x-mu)/std standardization or spectral norm."""

    hypersphere_radius: Literal["learnable"] | float = 1.0
    """When hypersphere constraint is enabled, sets the hypersphere radius (float), or sets it as a learnable scale."""

    hypersphere_update: bool = True
    """If enabled, then updates will also be projected to the hypersphere."""

    hypersphere_update_embeddings: bool = True
    """If disabled, hypersphere_update normalization is skipped for embedding parameters."""

    hypersphere_embeddings: bool = False
    """If enabled, then embeddings will also be normalized."""

    hypersphere_embedding_mode: Optional[Literal["row", "col", "rowcol", "flat"]] = None
    """When set, overrides hypersphere_mode for embedding/output parameters. Also implies hypersphere_embeddings."""

    hypersphere_split_heads: bool = False
    """If enabled, then each q,k,v head matrix will be normalized separately."""

    hypersphere_split_heads_update: bool = False
    """If enabled, then each q,k,v head matrix will be normalized separately."""

    hypersphere_project: bool = False
    """If enabled, do u - (w·u/||w||²) before the momentum accumulation."""

    hypersphere_soft: bool = False
    """If enabled, do R*w/max(||w||, R) instead of just R*w/||w||."""

    qk_layernorm_frozen: bool = False

    weight_decay_method: Literal["decoupled", "independent"] = "decoupled"

    use_orthogonal_updates: bool = False

    use_orthogonal_embeddings: bool = True

    poor_mans_ortho: bool = False
    """If enabled, use _normalize instead of _orthogonalize in the Muon branch (cheaper approximation)."""

    use_lion: bool = False
    """If enabled, use Lion-style sign-momentum updates (like Adam but without the second moment).
    beta1 controls the update interpolation, beta2 controls the momentum EMA."""

    # AdEMAMix
    ademamix_alpha: float = 2.0
    """AdEMAMix alpha coefficient mixing the slow and fast EMAs."""
    
    ademamix_beta3: float = 0.9999
    """AdEMAMix beta3 parameter for slow momentum."""
    
    ademamix_beta3_warmup: Optional[int] = None
    """Number of warmup steps used to increase beta3."""
    
    ademamix_alpha_warmup: Optional[int] = None
    """Number of warmup steps used to increase alpha."""


    #######################
    # Distributed optimizer
    #######################
    use_distributed_optimizer: bool = False
    """Distribute optimizer state over data-parallel replicas."""

    overlap_param_gather: bool = False
    """If true, overlap param all-gather with forward compute. 
        This argument is intended to have the same value as the "overlap_param_gather" argument 
        in the "distributed_data_parallel_config.py" file. In the optimizer, this argument is 
        only used when "reuse_grad_buf_for_mxfp8_param_ag=True & fp8_param_gather=True".
    """

    overlap_param_gather_with_optimizer_step: bool = False
    """If true, overlap param all-gather of first bucket with optimizer step."""

    #######################
    # Optimizer Offload
    #######################

    optimizer_cpu_offload: bool = False
    """If True, offload optimizer states tensor and compute to CPU."""

    optimizer_offload_fraction: float = 0.0
    """Specifies the fraction of optimizer states to offload from GPU memory to CPU."""

    use_torch_optimizer_for_cpu_offload: bool = False
    """If True, use torch.optim.Optimizer for CPU offload."""

    overlap_cpu_optimizer_d2h_h2d: bool = False
    """
    When set to `True`, this flag enables overlapping of the CPU optimizer
    update process with the data transfer operations. This can help improve
    overall training efficiency by reducing idle time during data movement,
    allowing the optimizer to perform updates while gradients and parameters
    are being transferred between devices.
    """

    pin_cpu_grads: bool = True
    """If True, pin the optimizer gradients to CPU memory."""

    pin_cpu_params: bool = True
    """If True, pin the optimizer parameters to CPU memory."""

    ################
    # Miscellaneous
    ################
    clip_grad: float = 1.0
    """Gradient clipping based on global L2 norm."""

    log_num_zeros_in_grad: bool = False
    """If true, calculate and log the number of zeros in gradient."""

    barrier_with_L1_time: bool = False
    """If true, use barrier with level 1 time measurements."""

    timers: Optional[Callable] = None
    """Function to get timers."""

    config_logger_dir: str = ""
    """When non-empty, dumps entry-point configs to config_logger_dir"""

    def __post_init__(self):
        """Check the validity of the config."""

        # The following condition is used to avoid repetition in distrib_optimizer.py.
        # This is because in distrib_optimizer.py, the process to handle parameters are
        # different for different training precision settings. FP8 cases require different
        # handling while FP8 delayed scaling is an exception because the Adam optimizer in
        # TransformerEngine supports it in the kernel computation.
        # This is also the flag to determine the usage of param.grad or param.decoupled_grad
        self.use_precision_aware_optimizer_no_fp8_or_ds_fp8 = (
            self.use_precision_aware_optimizer
            and (
                self.main_params_dtype != torch.float32
                or (self.fp8_recipe is None or self.fp8_recipe == "delayed")
                or self.optimizer_cpu_offload
            )
        )

        if self.fp8_recipe == "mxfp8":
            if not self.reuse_grad_buf_for_mxfp8_param_ag:
                import warnings

                warnings.warn(
                    "mxfp8 without using reuse_grad_buf_for_mxfp8_param_ag and fp8_param_gather"
                    "will use significant amount additional GPU memory."
                    "Setting --reuse-grad-buf-for-mxfp8-param-ag and --fp8-param-gather is "
                    "recommended for mxfp8 training."
                )

        if self.use_precision_aware_optimizer:
            assert (
                self.optimizer == 'adam'
            ), '--use-precision-aware-optimizer only supported with adam'
            assert (
                self.use_distributed_optimizer
            ), '--use-precision-aware-optimizer only supported with distributed optimizer'

            if not is_te_min_version("2.1.0"):
                self.store_param_remainders = False

            # Only the FusedAdam in TE and HybridDeviceOptimizer supports
            # --use-precision-aware-optimizer.
            # TODO: Remove this check when apex's FusedAdam is no longer used.
            if self.optimizer_cpu_offload:
                return
            try:
                import inspect

                # TODO: Move this below?
                from transformer_engine.pytorch.optimizers import FusedAdam as Adam

                adam_args = inspect.signature(Adam).parameters
                arg_names = [
                    'master_weight_dtype',
                    'exp_avg_dtype',
                    'exp_avg_sq_dtype',
                    'use_decoupled_grad',
                ]
                for name in arg_names:
                    assert name in adam_args, (
                        "Current FusedAdam of TE doesn't support --use-precision-aware-optimizer, "
                        "please update TE version."
                    )
            except ImportError:
                raise RuntimeError(
                    '--use-precision-aware-optimizer requires FusedAdam from TransformerEngine, '
                    'but not found.'
                )
        else:
            assert (
                self.main_grads_dtype == torch.float32
            ), "main_grads_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.main_params_dtype == torch.float32
            ), "main_params_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_dtype == torch.float32
            ), "exp_avg_dtype can only be fp32 when not using precision-aware optimizer"
            assert (
                self.exp_avg_sq_dtype == torch.float32
            ), "exp_avg_sq_dtype can only be fp32 when not using precision-aware optimizer"


@dataclass
class AdamOptimizerConfig(OptimizerConfig):
    """Adam optimizer configuration object."""

    optimizer: str = 'adam'
    """Optimizer name."""

    adam_beta1: float = 0.9
    """First coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_beta2: float = 0.999
    """Second coefficient for computing running averages of gradient and its square in Adam
    optimizer.
    """

    adam_eps: float = 1e-08
    """Term added to the denominator to improve numerical stability in Adam optimizer."""


@dataclass
class SGDOptimizerConfig(OptimizerConfig):
    """SGD optimizer configuration object."""

    optimizer: str = 'sgd'
    """Optimizer name."""

    sgd_momentum: float = 0.9
    """Momentum factor for SGD optimizer."""


@dataclass
class AdemamixOptimizerConfig(OptimizerConfig):
    """SGD optimizer configuration object."""

    optimizer: str = 'ademamix'
    """Optimizer name."""


class MasterOptimizerConfig(OptimizerConfig):
    optimizer: str = 'master'
